#!/usr/bin/env bash
# Copy the shared runtime, a style kit and a story into a film project (HyperFrames only serves the project dir).
# Usage: sync.sh <project-dir> <style> <story>
#   <story> is a story folder (holding story.json) or the name of a bundled one under explainer/stories/
# Writes <project>/lib/{core.js, sfxlib.py, kit/…, story.js} and copies the story's audio/narration.wav to
# assets/audio/narration.wav when the project has none yet.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"
PROJECT="$(cd "$1" && pwd -P)"; STYLE="$2"; STORY="$3"
[[ -f "$STORY/story.json" ]] || STORY="$ROOT/stories/$STORY"
STORY="$(cd "$STORY" 2>/dev/null && pwd -P)" || { echo "no story: $3" >&2; exit 1; }
[[ -d "$ROOT/kits/$STYLE" ]] || { echo "no kit: $STYLE (one of: $(ls "$ROOT/kits" | tr '\n' ' '))" >&2; exit 1; }
[[ -f "$STORY/story.json" ]] || { echo "no story.json in $STORY (run tools/story.py first)" >&2; exit 1; }
mkdir -p "$PROJECT/lib/kit" "$PROJECT/assets/audio"
cp "$ROOT/core/core.js" "$ROOT/core/sfxlib.py" "$PROJECT/lib/"
rsync -a --delete --exclude starter "$ROOT/kits/$STYLE/" "$PROJECT/lib/kit/"
{ printf '/* generated by tools/sync.sh from %s/story.json — edit the story, not this file */\nwindow.STORY = ' "$(basename "$STORY")"; cat "$STORY/story.json"; printf ';\n'; } > "$PROJECT/lib/story.js"
if [[ ! -f "$PROJECT/assets/audio/narration.wav" ]]; then
  if [[ -f "$STORY/audio/narration.wav" ]]; then
    cp "$STORY/audio/narration.wav" "$PROJECT/assets/audio/narration.wav"
  else   # e.g. a bundled story (audio is not committed): a silent track of the narration's length keeps the film whole
    LEN="$(python3 -c 'import json,sys; s=json.load(open(sys.argv[1])); print((s.get("recap") or {}).get("start") or s["duration"])' "$STORY/story.json")"
    ffmpeg -v error -y -f lavfi -t "$LEN" -i anullsrc=r=48000:cl=mono "$PROJECT/assets/audio/narration.wav"
    echo "note: $(basename "$STORY") has no audio/narration.wav — using $LEN s of silence (voice it with tools/story.py)" >&2
  fi
fi
echo "synced core + kit:$STYLE + story:$(basename "$STORY") → $PROJECT/lib"
